name: 📧 Notificar Despliegue

on:
  push:
    branches:
      - main 

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Success Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "🚀 BookMark: Despliegue iniciado en Render"
          to: olgacantalejog@gmail.com
          html_body: "El nuevo código ha sido subido a GitHub y Render está procesando el despliegue automático."