name: 🚀 CD - Semantic Release

on:
  push:
    branches: [ main ] 

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate Next Version
        id: semantic
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(feat)"
          version_format: "${major}.${minor}.${patch}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.semantic.outputs.version }}
          name: Release v${{ steps.semantic.outputs.version }}
          generate_release_notes: true
          # Usamos el token automático de GitHub
          token: ${{ secrets.GITHUB_TOKEN }}